
spring:
  application:
    name: PDP_CRM
  datasource:
    url: jdbc:postgresql://localhost:5432/pdp_crm
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

    generate-ddl: true
  jwt:
    secretKey: rscbHc219Dza6S6vb5N/HlFzfz4P21NLwb3qvwtcw9TtmfGuJfHkRziIGCsXdxhU
    accessTokenExpiredTime: 86400000
    refreshTokenExpiration: 604800000

server:
  port: 8080